#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Aug 25 08:16:58 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1756081018764
maven-metadata-jmall-snapshots.xml.error=
maven-metadata-jmall-snapshots.xml.lastUpdated=1756081018787
