#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Oct 16 10:01:01 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1760580061222
maven-metadata-jmall-snapshots.xml.lastUpdated=1760580061254
