#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Aug 20 14:56:28 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1755672988489
maven-metadata-jmall-snapshots.xml.error=
maven-metadata-jmall-snapshots.xml.lastUpdated=1755672988496
