#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Sep 03 13:17:51 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1756876671289
maven-metadata-jmall-snapshots.xml.lastUpdated=1756876671292
