#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Oct 15 15:32:47 CST 2025
maven-metadata-gsmmp-snapshots.xml/5b77a61417c8322e56a7250c1abc6c81b3b377d2@default-gsmmp-snapshots-https\://artifactory.anta.com/artifactory/gsmmp-maven-virtual/.lastUpdated=1760513567551
maven-metadata-jmall-snapshots.xml.error=
maven-metadata-jmall-snapshots.xml.lastUpdated=1760513567555
maven-metadata-gsmmp-snapshots.xml.error=Could not transfer metadata com.anta.mall\:mall-base-anta\:1.0-SNAPSHOT/maven-metadata.xml from/to gsmmp-snapshots (https\://artifactory.anta.com/artifactory/gsmmp-maven-virtual)\: status code\: 403, reason phrase\: Forbidden (403)
