#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Sep 28 17:52:19 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1759053139282
maven-metadata-jmall-snapshots.xml.error=
maven-metadata-jmall-snapshots.xml.lastUpdated=1759053139282
