#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Sep 20 14:37:29 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1758350249679
maven-metadata-jmall-snapshots.xml.error=
maven-metadata-jmall-snapshots.xml.lastUpdated=1758350249682
