#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Sep 20 14:37:02 CST 2025
maven-metadata-gsmmp-snapshots.xml/5b77a61417c8322e56a7250c1abc6c81b3b377d2@default-gsmmp-snapshots-https\://artifactory.anta.com/artifactory/gsmmp-maven-virtual/.lastUpdated=1758350222363
maven-metadata-jmall-snapshots.xml.error=
maven-metadata-jmall-snapshots.xml.lastUpdated=1758350222366
maven-metadata-gsmmp-snapshots.xml.error=Could not transfer metadata com.anta.mall\:goods-commons\:3.1.0-SNAPSHOT/maven-metadata.xml from/to gsmmp-snapshots (https\://artifactory.anta.com/artifactory/gsmmp-maven-virtual)\: status code\: 403, reason phrase\: Forbidden (403)
