#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Jun 19 14:12:33 CST 2025
maven-metadata-snapshots.xml.lastUpdated=1750313553661
maven-metadata-anta_internal.xml/@default-anta_internal-http\://10.211.238.135\:8081/nexus/content/groups/anta/.lastUpdated=1750313553659
maven-metadata-HuaweiCloudSDK.xml.error=
maven-metadata-ali-repository-central.xml.lastUpdated=1750313553658
maven-metadata-snapshots.xml.error=
maven-metadata-HuaweiCloudSDK.xml.lastUpdated=1750313553660
maven-metadata-anta_internal.xml.error=Could not transfer metadata org.springframework.cloud\:spring-cloud-starter-config\:2.0.0.BUILD-SNAPSHOT/maven-metadata.xml from/to anta_internal (http\://10.211.238.135\:8081/nexus/content/groups/anta/)\: transfer failed for http\://10.211.238.135\:8081/nexus/content/groups/anta/org/springframework/cloud/spring-cloud-starter-config/2.0.0.BUILD-SNAPSHOT/maven-metadata.xml
maven-metadata-ali-repository-central.xml.error=
