#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Oct 15 15:25:27 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1760513127925
maven-metadata-jmall-snapshots.xml.error=
maven-metadata-gsmmp-virtual.xml.lastUpdated=1760513127923
maven-metadata-jmall-snapshots.xml.lastUpdated=1760513127929
