#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Oct 15 15:46:24 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1760514384934
maven-metadata-jmall-snapshots.xml.error=
maven-metadata-gsmmp-virtual.xml.lastUpdated=1755671774626
maven-metadata-jmall-snapshots.xml.lastUpdated=1760514384951
