#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Oct 15 15:23:00 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1760512980442
maven-metadata-jmall-snapshots.xml.error=
maven-metadata-jmall-snapshots.xml.lastUpdated=1760512980446
