#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Oct 15 15:32:43 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1760513563101
maven-metadata-jmall-snapshots.xml.error=
maven-metadata-jmall-snapshots.xml.lastUpdated=1760513563104
