#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Sep 03 13:17:44 CST 2025
maven-metadata-gsmmp-snapshots.xml.lastUpdated=1756876664942
maven-metadata-jmall-snapshots.xml.lastUpdated=1756876664945
